[package]
name = "imezx/fastnet2"
version = "0.0.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"
description = "The successor of FastNet, FastNet2 is a incredible and powerful networking library."

[dependencies]